spring:
  application:
    name: cesi-zen-back

  datasource:
    url: jdbc:postgresql://localhost:5432/cesizenDb
    username: cesizenUser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:certs/cesizen-local.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: cesizen-local

security:
  jwt:
    secret: long-random-secret-for-cesizen-project
    issuer: cesi-zen-back
    access-token-validity-minutes: 15

app:
  frontend:
    reset-password-url: https://localhost:8443/reset-password

  account:
    inactivity-days: 90

  diagnostic:
    retention-days: 365
    purge-cron: "0 0 23 * * *"

  security:
    allowed-origins:
      - https://localhost:4200
      - http://localhost:4200
      - https://localhost:8443
      - http://localhost:8080